version: "2"
services:
  hideapic:
    build: .
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - redis
  redis:
    image: "redis:alpine"
  selenium:
    ports:
      - "4444:4444"
      - "5900:5900"
    image: selenium/standalone-chrome-debug
