version: '2.1'
services:
  hideapic:
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      interval: 5s
      retries: 1
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - redis
  redis:
    image: "redis:alpine"
